package com.nef.notenoughfakepixel.feature;

public final class FeatureDefaults {
    private FeatureDefaults() {}

    public static void register() {
        String[][] groups = {
            {"qol.chat_cleaner", "Chat Cleaner", "Quality of Life"},
            {"qol.chat_disable_friend_join", "Disable Friend Join Messages", "Quality of Life"},
            {"qol.chat_disable_info_watchdog", "Disable Info/Watchdog Messages", "Quality of Life"},
            {"qol.chat_disable_selling_ranks", "Disable Selling Rank Messages", "Quality of Life"},
            {"qol.copy_chat_message", "Copy Chat Message", "Quality of Life"},
            {"qol.disable_block_break_particles", "Disable Block Breaking Particles", "Quality of Life"},
            {"qol.hide_flaming_fists", "Hide Flaming Fists", "Quality of Life"},
            {"qol.hide_players_armor", "Hide Player Armor", "Quality of Life"},
            {"qol.hide_dead_mobs", "Hide Dead Mobs", "Quality of Life"},
            {"qol.hide_falling_blocks", "Hide Falling Blocks", "Quality of Life"},
            {"qol.smol_people", "Smol People", "Quality of Life"},
            {"qol.disable_hyperion_explosions", "Disable Hyperion Explosions", "Quality of Life"},
            {"qol.disable_thunderlord_bolts", "Disable Thunderlord Bolts", "Quality of Life"},
            {"qol.golden_enchants", "Golden Enchants", "Quality of Life"},
            {"qol.disable_potion_effects_inventory", "Disable Potion Effects in Inventory", "Quality of Life"},
            {"qol.missing_accessories", "Missing Accessories", "Quality of Life"},
            {"qol.ender_nodes", "Ender Nodes Highlighter", "Quality of Life"},
            {"farming.crop_height", "Crop Height", "Farming"},
            {"fishing.countdown", "Fishing Countdown", "Fishing"},
            {"fishing.legendary_notifier", "Legendary Sea Creature Notifier", "Fishing"},
            {"fishing.trophy_notifier", "Trophy Fish Notifier", "Fishing"},
            {"dungeons.leap_gui", "Custom Leap GUI", "Dungeons"},
            {"dungeons.terminal_gui", "Custom Terminal GUI", "Dungeons"},
            {"dungeons.blood_ready", "Blood Ready Title", "Dungeons"},
            {"dungeons.boulder_solver", "Boulder Solver", "Dungeons"},
            {"dungeons.silverfish_solver", "Silverfish Solver", "Dungeons"},
            {"dungeons.wither_doors", "Wither Doors Highlight", "Dungeons"},
            {"dungeons.teleport_maze", "Teleport Maze Solver", "Dungeons"},
            {"dungeons.terminal_waypoints", "Terminal Waypoints", "Dungeons"},
            {"dungeons.auto_ready", "Auto Ready", "Dungeons"},
            {"dungeons.auto_close_secrets", "Auto Close Secret Chests", "Dungeons"},
            {"dungeons.three_weirdos", "Three Weirdos Solver", "Dungeons"},
            {"dungeons.spirit_bow_tracer", "Spirit Bow Tracer", "Dungeons"},
            {"dungeons.custom_splus", "Custom S+ Message", "Dungeons"},
            {"dungeons.splus_reminder", "S+ Reminder", "Dungeons"},
            {"dungeons.starred_mob_display", "Starred Mob Display", "Dungeons"},
            {"dungeons.fel_display", "Fel Position Display", "Dungeons"},
            {"dungeons.bat_display", "Bat Position Display", "Dungeons"},
            {"dungeons.m7_dragon_highlight", "M7 Dragon Highlight", "Dungeons"},
            {"dungeons.m7_relic_waypoints", "M7 Relic Waypoints", "Dungeons"},
            {"mining.drill_animation_reset", "Drill Animation Reset Fix", "Mining"},
            {"mining.ability_ready", "Mining Ability Ready Notifier", "Mining"},
            {"mining.dwarven_waypoints", "Dwarven Waypoints", "Mining"},
            {"mining.drill_fuel_overlay", "Drill Fuel Overlay", "Mining"},
            {"mining.ability_cooldown", "Mining Ability Cooldown Overlay", "Mining"},
            {"mining.commissions_overlay", "Commissions Overlay", "Mining"},
            {"mining.mithril_powder", "Mithril Powder Overlay", "Mining"},
            {"mining.crystal_map", "Crystal Hollows Map", "Mining"},
            {"mining.crystal_waypoints", "Crystal Hollows Waypoints", "Mining"},
            {"mining.treasure_notifier", "Treasure Found Notifier", "Mining"},
            {"mining.precursor_city_overlay", "Precursor City Overlay", "Mining"},
            {"mining.automaton_overlay", "Automaton Overlay", "Mining"},
            {"mining.metal_detector", "Metal Detector Guesser", "Mining"},
            {"mining.worm_notifier", "Worm Notifier", "Mining"},
            {"mining.mines_of_divan", "Mines of Divan Overlay", "Mining"},
            {"experiment.chronomatron", "Chronomatron Solver", "Experimentation"},
            {"experiment.ultrasequencer", "Ultrasequencer Solver", "Experimentation"},
            {"experiment.prevent_missclicks", "Prevent Missclicks", "Experimentation"},
            {"chocolate.best_rabbit", "Best Rabbit Helper", "Chocolate Factory"},
            {"chocolate.hunt_eggs", "Hoppity Hunt Egg Waypoints", "Chocolate Factory"},
            {"chocolate.new_egg_notifier", "New Egg Notifier", "Chocolate Factory"},
            {"chocolate.egg_timer", "Egg Timer", "Chocolate Factory"},
            {"crimson.boss_notifier", "Boss Notifier", "Crimson Isle"},
            {"crimson.ashfang_helper", "Ashfang Helper", "Crimson Isle"},
            {"diana.burrow_guess", "Burrow Guess", "Diana"},
            {"diana.warp_keybind", "Diana Warp Keybind", "Diana"},
            {"diana.burrow_waypoints", "Diana Burrow Waypoints", "Diana"},
            {"diana.gaia_helper", "Gaia Construct Helper", "Diana"},
            {"diana.lynx_helper", "Siamese Lynx Helper", "Diana"},
            {"diana.inquisitor", "Minos Inquisitor Helper", "Diana"},
            {"diana.inquisitor_outline", "Inquisitor Outline", "Diana"},
            {"slayers.beacon_waypoints", "Voidgloom Beacon Waypoints", "Slayers"},
            {"slayers.miniboss_alert", "Miniboss Spawn Alert", "Slayers"},
            {"slayers.health_display", "Slayer Health Display", "Slayers"},
            {"slayers.boss_timer", "Slayer Boss Timer", "Slayers"},
            {"slayers.blaze_pillar", "Blaze Pillar Title", "Slayers"},
            {"slayers.blaze_attunements", "Blaze Attunements", "Slayers"}
        };
        for (String[] row : groups) FeatureRegistry.register(row[0], row[1], row[2], true);
    }
}
